### ISSUE TITLE
Cyphon installer ISO Problems and Erros

### ISSUE THREAD

**Issue by DestruidorPT** [cyphonmdr/cyphon#712]
The installation of your software contains problems, I have already followed the instructions of the two sites (https://www.cyphon.io/download and https://cyphon.readthedocs.io/en/latest/getting-started/install-cyphon.html) and even then this error persists. 
![image](https://user-images.githubusercontent.com/43963417/80163314-afa77a80-85cd-11ea-99a1-ef7de979c1cb.png)
It would not be easier to provide an OVA is that the ISO installation Cyphon has not been working.

**Comment by phuong7809** [comment]
You fix as instructed  @mikelv702, and edit in file common-services.yml in cyphondock:
replace  https://github.com/controlscanmdr/cyphon.git with /opt/cyphon

**Comment by DestruidorPT** [comment]
Thx @phuong7809, now is running.
The solution for this problem is this:

1st step:
Replace in the file /opt/cyphondock/common-services.yml with 'https://github.com/controlscanmdr/cyphon.git' with '/opt/cyphon';

2st step:
Comment or remove from this file /opt/cyphon/Dockerfile this code 
'--repository http://dl-5.alpinelinux.org/alpine/edge/main/
--repository http://dl-5.alpinelinux.org/alpine/edge/testing/
--repository http://dl-5.alpinelinux.org/alpine/edge/community/ \';

3st step:
Change the version of maxminddb from 1.4.1 to 1.5.2 (Last Version) in the file /opt/cyphon/requerements.txt

4st step:
Done! Now start the service 
'sudo systemctl start cyphon'

**Comment by DestruidorPT** [comment]
Hi executed this commands:
$ sudo docker exec -it cyphondock_cyphon_1 sh
$ python manage.py migrate
Did you @phuong7809 get this erro:
![image](https://user-images.githubusercontent.com/43963417/80196546-785cbc00-8615-11ea-91f2-be1b4d603285.png)

**Comment by DestruidorPT** [comment]
I still can't solve the error, I've tried different versions of gdal, but it still gives the error:
`django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.`

**Comment by jevis2020** [comment]
Hi, working in Virtualbox Ubuntu VM 
Executed the command
$ python manage.py migrate

Any fix for this error
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.

**Comment by jevis2020** [comment]
Ok I am still seeing this issue, any suggestions or fix would be appreciated.

**Comment by fatalglitch** [comment]
Sorry, this project is no longer actively maintained.
